# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, aeson, ansiTerminal, bifunctors, cmdargs, cpphs
, dataDefault, deepseq, Diff, filemanip, filepath, fingertree
, ghcPaths, hashable, hscolour, intern, liquidFixpoint, mtl
, optparseApplicative, parsec, syb, tagged, tasty, tastyHunit
, tastyRerun, text, time, unorderedContainers, vector
}:

cabal.mkDerivation (self: {
  pname = "liquidhaskell";
  version = "0.2.0.0";
  sha256 = "0ymf8fzq9lsq3ibk7r1rql5wa714gk16qmwflvshiw0kdgcc7fcl";
  isLibrary = true;
  isExecutable = true;
  buildDepends = [
    aeson ansiTerminal bifunctors cmdargs cpphs dataDefault deepseq
    Diff filemanip filepath fingertree ghcPaths hashable hscolour
    intern liquidFixpoint mtl parsec syb text time unorderedContainers
    vector
  ];
  testDepends = [
    filepath optparseApplicative tagged tasty tastyHunit tastyRerun
  ];
  meta = {
    homepage = "http://goto.ucsd.edu/liquidhaskell";
    description = "Liquid Types for Haskell";
    license = "GPL";
    platforms = self.ghc.meta.platforms;
  };
})
